USE USERS;

DECLARE @CONTEO FLOAT = 50;
IF (SELECT COUNT(*) FROM CAJA WHERE DINERO = @CONTEO) > 1
BEGIN
    PRINT CAST(@CONTEO AS VARCHAR) + ' HAY UN VALOR QUE ESTÁ DUPLICADO';
END;
ELSE BEGIN
    PRINT 'NO HAY DUPLICIDAD';
END;