USE USERS;

-- INSERT EN USERS
-- INSERT INTO USERS (ID, Nombre, Apellido1, Apellido2)
-- VALUES ('1', 'Aleg', 'Arenales', 'Alonso');
-- SELECT * FROM USERS;


-- -- INSERT EN CAJA
-- INSERT INTO CAJA (DINERO, DIA, SEMANA, MES, AÑO)
-- VALUES (50.00, DAY(GETDATE()), DATEPART(ISO_WEEK, GETDATE()), MONTH(GETDATE()), YEAR(GETDATE()));
INSERT INTO CAJA (DINERO, DIA, SEMANA, MES, AÑO)
VALUES (34, DAY(GETDATE()), DATEPART(ISO_WEEK, GETDATE()), MONTH(GETDATE()), YEAR(GETDATE()));

