IF EXISTS (SELECT 1 FROM sys.databases where name = 'USERS')
BEGIN
    print 'La base de datos existe';
END
ELSE
BEGIN
    print 'La base de datos no existe';
    CREATE DATABASE USERS;
END

USE USERS;
CREATE TABLE USERS(
    ID nvarchar(10) NOT NULL,
    Nombre nvarchar(20),
    Apellido1 nvarchar(20),
    Apellido2 nvarchar(20)
);
-- DROP TABLE USERS;

CREATE TABLE CAJA(
    DINERO FLOAT,
    DIA FLOAT,
    SEMANA FLOAT,
    MES FLOAT,
    AÑO FLOAT
);
-- DROP TABLE CAJA;


-----------CAFETERIA------------

USE CAFETERIA;

CREATE TABLE CAFE_CHOCOLATE(
    ID INTEGER,
    NOMBRE NVARCHAR(200),
    PRECIO FLOAT,
    STOCK INTEGER
);
-- DROP TABLE CAFE_CHOCOLATE;

CREATE TABLE INFUSIONES(
    ID INTEGER,
    NOMBRE NVARCHAR,
    PRECIO FLOAT,
    STOCK INTEGER
);
-- DROP TABLE INFUSIONES;

CREATE TABLE AGUAS(
    ID INTEGER,
    NOMBRE NVARCHAR,
    PRECIO FLOAT,
    STOCK INTEGER
);
-- DROP TABLE AGUAS;

CREATE TABLE ZUMOS(
    ID INTEGER,
    NOMBRE NVARCHAR,
    PRECIO FLOAT,
    STOCK INTEGER
);
-- DROP TABLE ZUMOS;

CREATE TABLE REFRESCOS(
    ID INTEGER,
    NOMBRE NVARCHAR,
    PRECIO FLOAT,
    STOCK INTEGER
);
-- DROP TABLE REFRESCOS;

CREATE TABLE CERVEZAS(
    ID INTEGER,
    NOMBRE NVARCHAR,
    PRECIO FLOAT,
    STOCK INTEGER
);
-- DROP TABLE CERVEZAS;


-----------COCINA------------
USE COCINA;

CREATE TABLE BOLLERIA(
    ID INTEGER,
    NOMBRE NVARCHAR,
    PRECIO FLOAT,
    STOCK INTEGER
);
-- DROP TABLE BOLLERIA;

CREATE TABLE BOCADILLOS(
    ID INTEGER,
    NOMBRE NVARCHAR,
    PRECIO FLOAT,
    STOCK INTEGER
);
-- DROP TABLE BOCADILLOS;

CREATE TABLE SNACKS(
    ID INTEGER,
    NOMBRE NVARCHAR,
    PRECIO FLOAT,
    STOCK INTEGER
);
-- DROP TABLE SNACKS;